---
driver:
  name: docker

provisioner:
  name: chef_solo

platforms:
  - name: ubuntu
  - name: centos

suites:
  - name: default
    run_list:
      - recipe[build-essential]
      - recipe[autoconf]
    attributes:
