---
driver:
  name: docker
  binary: /usr/local/bin/docker
  socket: <%= ENV['DOCKER_HOST'] %>

provisioner:
  name: chef_solo

platforms:
  - name: ubuntu
  - name: centos

suites:
  - name: default
    run_list:
      - recipe[autoconf::default]
    attributes:
