---
driver:
  name: docker

provisioner:
  name: chef_solo

platforms:
  - name: ubuntu-12.04
  - name: centos-6.4

suites:
  - name: default
    run_list:
      - recipe[autoconf]
  - name: version
    run_list:
      - recipe[autoconf]
    attributes:
      autoconf:
        version: 2.66
  - name: prefix
    run_list:
      - recipe[autoconf]
    attributes:
      autoconf:
        prefix: "/opt/local"
