language: ruby
rvm: 2.2.2

sudo: true

cache: bundler

gemfile:
  - Gemfile

install:
  - curl -sLo - https://raw.githubusercontent.com/moul/travis-docker/feature-network/install.sh | sh -xe
  - bundle install

script:
  - ./run bundle exec kitchen verify
