language: ruby

sudo: true

cache:
  directories:
    - vendor/bundle

gemfile:
  - Gemfile

install:
  - curl -sLo - http://j.mp/install-travis-docker | sh -xe
  - bundle install --deployment

script:
  - bundle exec kitchen verify
